### ISSUE TITLE
Master in HA with external LB

### ISSUE THREAD

**Issue by cloudcafetech** [clemenko/rke_airgap_install#11]
First of all, thanks for valuable repo.

Looking for HA mode for 3 Master with external LB.

**Comment by clemenko** [comment]
Configuring a HA cluster with an LB gets a lot more complicated in an air gap network. The simpliest idea is to use multiple DNS A records to point to the 3 master nodes. The config is similar to the first node. Here is an old script that showed it : https://github.com/clemenko/rke2/blob/main/deprecated_harv.sh#L109

Hope this helps. But to keep this repo simple I want to stay away from HA mode here.
