### ISSUE TITLE
ligne 194 - small error

### ISSUE THREAD

**Issue by MozeBaltyk** [clemenko/rke_airgap_install#13]
Hello Clemenko 

Congrats for this new version of the rke airgap project. Big improvement. Hauler is much better than oc-mirror. 

Just found small skitch. `install` does not really make sens (or it's a command that I don't know on rocky linux...)

```bash 
  # install
  if [ ! -f /usr/local/bin/hauler ]; then  install -m 755 hauler /usr/local/bin || fatal "Failed to Install Hauler to /usr/local/bin" ; fi
  ```
also here line around 400

```bash
install -m 755 linux-amd64/helm /usr/local/bin || fatal "Failed to install helm to /usr/local/bin"
```

**Comment by clemenko** [comment]
Thanks. we do quite like hauler. 

Curious. This is from a clean Rocky VM. 
```
[root@flux ~]# which install
/usr/bin/install
```

The install command will copy the `hauler` binary to a location that is in path. Did this work for you?

**Comment by MozeBaltyk** [comment]
Oki you are right, I have this command on my RHEL8. I just did not know that such a command. 

I was playing with gitlab actions which are on ubuntu about the build package to have it available on a s3 bucket. 

My laptop  is really getting old so I am learning how to make the job done on the cloud. 😏

**Comment by clemenko** [comment]
I personally love Digitalocean. They have some really cheap vms. And I let them only run when I am playing.

**Comment by clemenko** [comment]
Closing since this is not an issue. Please feel free to open a new issue if anything comes up.
