### ISSUE TITLE
Getting Error when loading Rancher

### ISSUE THREAD

**Issue by rickwoomer** [clemenko/rke_airgap_install#20]
I am running into an issue when trying to install rancher.  
=======================================
./hauler_all_the_things.sh rancher
[info] deploying cert-manager
Release "cert-manager" does not exist. Installing it now.
Pulled: 10.19.1.4:5000/hauler/cert-manager:v1.15.3
Digest: sha256:3a987ea13d85c4fa52258aa63d16842431bf5fd3fd310db1fbbadd51eea57f95
NAME: cert-manager
LAST DEPLOYED: Wed Aug 21 16:27:25 2024
NAMESPACE: cert-manager
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
cert-manager v1.15.3 has been deployed successfully!

In order to begin issuing certificates, you will need to set up a ClusterIssuer
or Issuer resource (for example, by creating a 'letsencrypt-staging' issuer).

More information on the different types of issuers and how to configure them
can be found in our documentation:

https://cert-manager.io/docs/configuration/

For information on how to configure cert-manager to automatically provision
Certificates for Ingress resources, take a look at the `ingress-shim`
documentation:

https://cert-manager.io/docs/usage/ingress/
[info] deploying rancher
Release "rancher" does not exist. Installing it now.
Pulled: 10.19.1.4:5000/hauler/rancher:2.8.5
Digest: sha256:fe07eb6fec5e42ab3f5316287db8be5ac050e6f0090683b6ce2dfd855c5d90c3
Error: 1 error occurred:
        * Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://rke2-ingress-nginx-controller-admission.kube-system.svc:443/networking/v1/ingresses?timeout=10s": no endpoints available for service "rke2-ingress-nginx-controller-admission"
=========
Pod Info

  kubectl get pods -A
NAMESPACE                         NAME                                                    READY   STATUS             RESTARTS   AGE
cattle-fleet-local-system         fleet-agent-65d746df47-csszk                            1/1     Running            0          20m
cattle-fleet-system               fleet-controller-5d6d97d978-lgbzw                       1/1     Running            0          21m
cattle-fleet-system               gitjob-d69c8bb44-wgx6k                                  1/1     Running            0          21m
cattle-provisioning-capi-system   capi-controller-manager-6f87d6bd74-48fkn                1/1     Running            0          19m
cattle-system                     helm-operation-56hz2                                    0/2     Completed          0          19m
cattle-system                     helm-operation-9qz4j                                    0/2     Completed          0          21m
cattle-system                     helm-operation-hlt4p                                    0/2     Completed          0          22m
cattle-system                     helm-operation-klctd                                    0/2     Completed          0          21m
cattle-system                     helm-operation-s9nwm                                    0/2     Completed          0          20m
cattle-system                     helm-operation-wvfxr                                    0/2     Completed          0          16m
cattle-system                     rancher-6c858b6866-275j4                                1/1     Running            0          25m
cattle-system                     rancher-webhook-b68c6d878-kdnpz                         1/1     Running            0          20m
cert-manager                      cert-manager-bbfd7cb76-f5jjz                            1/1     Running            0          26m
cert-manager                      cert-manager-cainjector-78845699cf-5r248                1/1     Running            0          26m
cert-manager                      cert-manager-webhook-6d8fc845f-6fftx                    1/1     Running            0          26m
kube-system                       cloud-controller-manager-d-charon-ceph.arl.psu.edu      1/1     Running            0          56m
kube-system                       etcd-d-charon-ceph.arl.psu.edu                          1/1     Running            0          56m
kube-system                       helm-install-rke2-canal-2s5k4                           0/1     Completed          0          56m
kube-system                       helm-install-rke2-coredns-m57gn                         0/1     Completed          0          56m
kube-system                       helm-install-rke2-ingress-nginx-qfcjv                   0/1     Completed          0          56m
kube-system                       helm-install-rke2-metrics-server-msq7j                  0/1     Completed          0          56m
kube-system                       helm-install-rke2-snapshot-controller-crd-tdzdd         0/1     Completed          0          56m
kube-system                       helm-install-rke2-snapshot-controller-hz8kt             0/1     Completed          1          56m
kube-system                       helm-install-rke2-snapshot-validation-webhook-h67s9     0/1     Completed          0          56m
kube-system                       kube-apiserver-d-charon-ceph.arl.psu.edu                1/1     Running            0          55m
kube-system                       kube-controller-manager-d-charon-ceph.arl.psu.edu       1/1     Running            0          56m
kube-system                       kube-proxy-c-charon-ceph.arl.psu.edu                    1/1     Running            0          31m
kube-system                       kube-proxy-d-charon-ceph.arl.psu.edu                    1/1     Running            0          56m
kube-system                       kube-scheduler-d-charon-ceph.arl.psu.edu                1/1     Running            0          56m
kube-system                       rke2-canal-28gx9                                        2/2     Running            0          31m
kube-system                       rke2-canal-g246l                                        2/2     Running            0          55m
kube-system                       rke2-coredns-rke2-coredns-565dfc7d75-mbbdh              1/1     Running            0          31m
kube-system                       rke2-coredns-rke2-coredns-565dfc7d75-xbqzx              1/1     Running            0          55m
kube-system                       rke2-coredns-rke2-coredns-autoscaler-6c48c95bf9-gcrvb   1/1     Running            0          55m
kube-system                       rke2-ingress-nginx-controller-crlvc                     0/1     ImagePullBackOff   0          28m
kube-system                       rke2-ingress-nginx-controller-tcmwb                     0/1     ImagePullBackOff   0          53m
kube-system                       rke2-metrics-server-c9c78bd66-f4qzv                     1/1     Running            0          53m
kube-system                       rke2-snapshot-controller-6f7bbb497d-zbslv               1/1     Running            0          53m
kube-system                       rke2-snapshot-validation-webhook-65b5675d5c-4dd45       1/1     Running            0          54m

**Comment by clemenko** [comment]
did you try to run `./hauler_all_the_things.sh rancher` a second time?

What OS? 

I was not able to recreate the issue.

**Comment by rickwoomer** [comment]
The installation was on RHEL8.  I was able to get this to work by repeating the steps.  When I repeated the build, I noticed that there was a large discrepancy in the size of the .zst file (a few hundred MB).  When I used the new .zst file, everything worked as advertised.

**Comment by clemenko** [comment]
awesome. sounds like something didn't get added the tar ball.
