### ISSUE TITLE
Ha setup

### ISSUE THREAD

**Issue by cloudcafetech** [clemenko/rke_airgap_install#24]
Nice !! 

Can we setup RKE2 HA using Hauler?

**Comment by clemenko** [comment]
absolutely. HA Rke2 is basically 3 control plane nodes and some DNS/LB/VIP for the worker nodes. I made a video on this : https://www.youtube.com/watch?v=Um_GVIL71xQ

You would still use hauler to bring all the bits and seed the images, charts, and files.

**Comment by clemenko** [comment]
Is this still an issue? Can we close this?

**Comment by clemenko** [comment]
Closing since there is no response.
