### ISSUE TITLE
longhorn function does not respect longhorn version variable

### ISSUE THREAD

**Issue by dmeiselman** [clemenko/rke_airgap_install#4]
Hey Andy, found another bug for ya:

The longhorn function has 1.3.2.tgz hard coded. The latest tarball is named longhorn-1.4.0.tgz

**Comment by clemenko** [comment]
thanks. 
changing to 
`  helm upgrade -i longhorn /opt/rancher/helm/longhorn-$($LONGHORN_VERSION | sed 's/v//g').tgz --namespace longhorn-system --create-namespace --set ingress.enabled=true --set ingress.host=longhorn.$DOMAIN --set global.cattle.systemDefaultRegistry=localhost:5000`

**Comment by dmeiselman** [comment]
ditto with rancher v2.7.0 at line 396

**Comment by clemenko** [comment]
good catch. found another. fixed. testing right now.

**Comment by clemenko** [comment]
all checks out.
