### ISSUE TITLE
Why Cert-manager is used for Rancher but not for Longhorn and NeuVector ? 

### ISSUE THREAD

**Issue by MozeBaltyk** [clemenko/rke_airgap_install#9]
just a question a small question. Maybe it would be worth to activate discussion on this project. To discuss those kind of topics ?

**Comment by clemenko** [comment]
good idea. Cert-manager is used for a self signed front door for Rancher. It needs a Certificate Authority (CA) for that. Cert-manager is the CA.

**Comment by MozeBaltyk** [comment]
So if I understand right, you are using Cert-manager just as CA for Rancher but do not self-sign SSL certificates for the URL ?

**Comment by clemenko** [comment]
The CA creates the self signed cert for Rancher.

**Comment by MozeBaltyk** [comment]
Not completely finished but ...  https://github.com/MozeBaltyk/rkub

**Comment by clemenko** [comment]
Closing for fun! lol please feel free to reopen if there is a need.
